version: "3.7"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=$MYSQL_NAME
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  web:
    build:
      context: .
    image: rdmolony/web
    volumes:
      - .:/app
    ports:
      - 8000:80
    command: sh run_tests.sh
    depends_on:
      - mysqldb
