version: "3.7"

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=$MYSQL_NAME
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:80
    command: ping mysqldb
    depends_on:
      - mysqldb
